# Generated by Django 6.0 on 2025-12-06 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PoolModelFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Series/family name, e.g. \'Aurora Series 52" Wall\'.', max_length=200)),
                ('brand', models.CharField(blank=True, help_text='Manufacturer/brand (e.g. Latham).', max_length=100)),
                ('pool_type', models.CharField(choices=[('above', 'Above-Ground'), ('semi', 'Semi-Inground'), ('inground_liner', 'Inground Liner')], help_text='Above-ground, semi-inground, or inground liner.', max_length=20)),
                ('shape', models.CharField(choices=[('round', 'Round'), ('rectangle', 'Rectangle')], help_text='Geometric shape for this family (round or rectangle for now).', max_length=20)),
                ('quality_label', models.CharField(blank=True, help_text="Marketing/quality label, e.g. 'Premium Steel', 'Signature', etc.", max_length=100)),
                ('supports_custom_depth', models.BooleanField(default=False, help_text='True if this family supports custom-depth options via special quote.')),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this pool family.')),
            ],
            options={
                'verbose_name': 'Pool Model Family',
                'verbose_name_plural': 'Pool Model Families',
                'ordering': ['brand', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StoreCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'Store Category',
                'verbose_name_plural': 'Store Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PoolVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diameter', models.DecimalField(blank=True, decimal_places=2, help_text='For round pools: diameter in feet. Leave blank for rectangles.', max_digits=5, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=2, help_text='For rectangles: length in feet.', max_digits=5, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, help_text='For rectangles: width in feet.', max_digits=5, null=True)),
                ('wall_height_inches', models.PositiveIntegerField(blank=True, help_text='Standard wall height in inches (for above/semi).', null=True)),
                ('depth_label', models.CharField(blank=True, help_text='Human-friendly depth description (e.g. \'3.5–5 ft\', \'52" Wall\').', max_length=100)),
                ('variant_price', models.DecimalField(decimal_places=2, help_text='Base price for this specific size/depth package.', max_digits=10)),
                ('install_days', models.DecimalField(decimal_places=1, default=1.0, help_text='Estimated number of install days for this variant.', max_digits=4)),
                ('install_daily_rate', models.DecimalField(decimal_places=2, default=0, help_text='Daily labor rate for this pool variant.', max_digits=10)),
                ('install_included_miles', models.PositiveIntegerField(default=0, help_text='Miles from base ZIP (34491) included before extra per-mile charges.')),
                ('install_per_mile_rate', models.DecimalField(decimal_places=2, default=0, help_text='Charge per mile beyond included miles.', max_digits=7)),
                ('is_active', models.BooleanField(default=True)),
                ('sku', models.CharField(blank=True, help_text='Optional SKU for this specific variant.', max_length=100, null=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='store.poolmodelfamily')),
            ],
            options={
                'verbose_name': 'Pool Variant',
                'verbose_name_plural': 'Pool Variants',
                'ordering': ['family', 'diameter', 'length', 'width'],
            },
        ),
        migrations.CreateModel(
            name='StoreItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('sku', models.CharField(blank=True, help_text='Internal SKU or manufacturer code.', max_length=100, null=True)),
                ('description_short', models.CharField(blank=True, help_text='Short description for listings.', max_length=255)),
                ('description_long', models.TextField(blank=True, help_text='Full description for product detail pages.')),
                ('price', models.DecimalField(decimal_places=2, help_text='Selling price for this item.', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_installable', models.BooleanField(default=False, help_text='If true, customer can choose installation for this item.')),
                ('install_base_rate', models.DecimalField(decimal_places=2, default=0, help_text='Base cost to install this item (labor only).', max_digits=10)),
                ('install_included_miles', models.PositiveIntegerField(default=0, help_text='Miles included before per-mile fee applies for this item.')),
                ('install_per_mile_rate', models.DecimalField(decimal_places=2, default=0, help_text='Charge per mile beyond included miles for installation.', max_digits=7)),
                ('free_shipping_with_install', models.BooleanField(default=False, help_text='If true, selecting installation removes shipping cost for this item.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Category such as Pump, Filter, Heater, Accessory, Chemical, etc.', on_delete=django.db.models.deletion.PROTECT, related_name='items', to='store.storecategory')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='store_store_slug_8c96ad_idx'), models.Index(fields=['sku'], name='store_store_sku_f352a8_idx')],
            },
        ),
    ]
