# Generated by Django 6.0 on 2025-12-06 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poolmodelfamily',
            name='ionizer_compatibility',
            field=models.CharField(choices=[('recommended', 'Recommended'), ('not_recommended', 'Not recommended')], default='recommended', help_text='Is this pool recommended for use with an ionizer system?', max_length=20),
        ),
        migrations.AddField(
            model_name='poolmodelfamily',
            name='salt_compatibility',
            field=models.CharField(choices=[('recommended', 'Recommended'), ('not_recommended', 'Not recommended')], default='recommended', help_text='Is this pool recommended for use with a salt system?', max_length=20),
        ),
    ]
