# Generated by Django 6.0 on 2025-12-06 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_poolmodelfamily_ionizer_compatibility_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poolmodelfamily',
            name='brand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='poolmodelfamily',
            name='ionizer_compatibility',
            field=models.CharField(choices=[('recommended', 'Recommended'), ('not_recommended', 'Not Recommended')], default='recommended', help_text='Ionizer system compatibility', max_length=20),
        ),
        migrations.AlterField(
            model_name='poolmodelfamily',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='poolmodelfamily',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='poolmodelfamily',
            name='pool_type',
            field=models.CharField(choices=[('above', 'Above-Ground'), ('semi', 'Semi-Inground'), ('inground_liner', 'Inground Liner')], max_length=20),
        ),
        migrations.AlterField(
            model_name='poolmodelfamily',
            name='quality_label',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='poolmodelfamily',
            name='salt_compatibility',
            field=models.CharField(choices=[('recommended', 'Recommended'), ('not_recommended', 'Not Recommended')], default='recommended', help_text='Saltwater system compatibility', max_length=20),
        ),
        migrations.AlterField(
            model_name='poolmodelfamily',
            name='shape',
            field=models.CharField(choices=[('round', 'Round'), ('rectangle', 'Rectangle')], max_length=20),
        ),
        migrations.AlterField(
            model_name='poolmodelfamily',
            name='supports_custom_depth',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='poolvariant',
            name='depth_label',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='poolvariant',
            name='diameter',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='poolvariant',
            name='install_daily_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='poolvariant',
            name='install_days',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='poolvariant',
            name='install_included_miles',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='poolvariant',
            name='install_per_mile_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='poolvariant',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='poolvariant',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='poolvariant',
            name='variant_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='poolvariant',
            name='wall_height_inches',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poolvariant',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='storeitem',
            name='free_shipping_with_install',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='storeitem',
            name='install_base_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='storeitem',
            name='install_included_miles',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='storeitem',
            name='install_per_mile_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='storeitem',
            name='is_installable',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PoolPackageComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_group', models.CharField(choices=[('pump', 'Pump'), ('filter', 'Filter'), ('heater', 'Heater'), ('ladder', 'Ladder / Entry'), ('sanitizer', 'Sanitizer'), ('plumbing', 'Plumbing / Hoses'), ('accessory', 'Accessory'), ('other', 'Other')], max_length=30)),
                ('is_default', models.BooleanField(default=False)),
                ('is_required', models.BooleanField(default=False)),
                ('is_upgrade_only', models.BooleanField(default=False)),
                ('option_group_code', models.CharField(blank=True, help_text='Items with the same code are mutually exclusive upgrade choices.', max_length=50)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pool_components', to='store.storeitem')),
                ('pool_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_components', to='store.poolvariant')),
            ],
            options={
                'verbose_name': 'Pool Package Component',
                'verbose_name_plural': 'Pool Package Components',
                'ordering': ['pool_variant', 'component_group', 'item__name'],
            },
        ),
    ]
