# Generated by Django 6.0 on 2025-12-06 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_poolmodelfamily_brand_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoolType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Pool Type',
                'verbose_name_plural': 'Pool Types',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='poolmodelfamily',
            name='pool_type',
        ),
        migrations.AddField(
            model_name='poolmodelfamily',
            name='pool_types',
            field=models.ManyToManyField(blank=True, help_text='Select all pool types this family can be installed as.', related_name='pool_families', to='store.pooltype'),
        ),
    ]
