# Generated by Django 6.0 on 2025-12-06 19:35

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_pooltype_remove_poolmodelfamily_pool_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Internal code, e.g. 'pool_freight', 'accessory_parcel'.", max_length=50, unique=True)),
                ('name', models.CharField(help_text='Human-readable name for this shipping group.', max_length=100, unique=True)),
                ('base_flat_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Base flat shipping rate (can be 0).', max_digits=10)),
                ('per_mile_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Optional per-mile shipping charge (0 = none).', max_digits=7)),
                ('free_with_install', models.BooleanField(default=False, help_text='If true, shipping is free when installation is purchased.')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Shipping Group',
                'verbose_name_plural': 'Shipping Groups',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='poolvariant',
            options={'ordering': ['family', 'shape', 'diameter', 'length', 'width'], 'verbose_name': 'Pool Variant', 'verbose_name_plural': 'Pool Variants'},
        ),
        migrations.RemoveField(
            model_name='poolmodelfamily',
            name='shape',
        ),
        migrations.AddField(
            model_name='poolvariant',
            name='shape',
            field=models.CharField(choices=[('round', 'Round'), ('oval', 'Oval'), ('rectangle', 'Rectangle')], default='round', help_text='Geometric shape for this specific configuration.', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='poolvariant',
            name='depth_label',
            field=models.CharField(blank=True, help_text='Human-friendly depth description (e.g. "52" Wall", "3.5–5 ft").', max_length=100),
        ),
        migrations.AlterField(
            model_name='poolvariant',
            name='diameter',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='For round/oval pools: diameter or long axis in feet.', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='poolvariant',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='For rectangle/oval: length in feet.', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='poolvariant',
            name='variant_price',
            field=models.DecimalField(decimal_places=2, help_text='Base price for this specific size/depth package.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='poolvariant',
            name='wall_height_inches',
            field=models.PositiveIntegerField(blank=True, help_text='Standard wall height in inches (for above/semi).', null=True),
        ),
        migrations.AlterField(
            model_name='poolvariant',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='For rectangle/oval: width in feet.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='poolvariant',
            name='shipping_group',
            field=models.ForeignKey(blank=True, help_text='Defines how this pool package is shipped when not installed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pool_variants', to='store.shippinggroup'),
        ),
        migrations.AddField(
            model_name='storeitem',
            name='shipping_group',
            field=models.ForeignKey(blank=True, help_text='Defines how this item is shipped.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_items', to='store.shippinggroup'),
        ),
    ]
