# Generated by Django 6.0 on 2025-12-07 13:21

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('allow_pool_installs', models.BooleanField(default=True)),
                ('allow_accessory_installs', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Service Area',
                'verbose_name_plural': 'Service Areas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ZipLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(help_text='5-digit ZIP (optionally ZIP+4).', max_length=10, unique=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('county', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('install_allowed', models.BooleanField(default=True)),
                ('permit_fee_pool', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('permit_fee_accessory', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('notes', models.TextField(blank=True)),
                ('service_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zip_locations', to='store.servicearea')),
            ],
            options={
                'verbose_name': 'ZIP Location',
                'verbose_name_plural': 'ZIP Locations',
                'ordering': ['state', 'county', 'zip_code'],
            },
        ),
    ]
