# Generated by Django 6.0 on 2025-12-07 13:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_servicearea_ziplocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default='default', help_text='Do not change. Used to ensure a single settings row.', max_length=50, unique=True)),
                ('permit_labor_hourly_rate', models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Hourly labor rate used to calculate permit labor charges.', max_digits=8)),
            ],
            options={
                'verbose_name': 'Global Settings',
                'verbose_name_plural': 'Global Settings',
            },
        ),
        migrations.RemoveField(
            model_name='ziplocation',
            name='permit_fee_accessory',
        ),
        migrations.RemoveField(
            model_name='ziplocation',
            name='permit_fee_pool',
        ),
        migrations.AddField(
            model_name='servicearea',
            name='permit_accessory_fee_base',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Base government permit cost for accessory installs in this area.', max_digits=8),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='permit_accessory_labor_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Admin labor hours expected for accessory permits in this area.', max_digits=5),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='permit_pool_fee_base',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Base government permit cost for pool installs in this area.', max_digits=8),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='permit_pool_labor_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Admin labor hours expected for pool permits in this area.', max_digits=5),
        ),
    ]
