# Generated by Django 6.0 on 2025-12-07 14:12

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_globalsettings_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicearea',
            options={'ordering': ['name'], 'verbose_name': 'County', 'verbose_name_plural': 'Counties'},
        ),
        migrations.AddField(
            model_name='order',
            name='permit_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='zip_code',
            field=models.CharField(blank=True, help_text='Customer ZIP/postal code for this job.', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='zip_location',
            field=models.ForeignKey(blank=True, help_text='Linked ZIP record (county, state, etc.).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='store.ziplocation'),
        ),
    ]
