# Generated by Django 6.0 on 2025-12-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_servicearea_options_order_permit_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='base_zip_code',
            field=models.CharField(default='34491', help_text='Primary business ZIP for distance calculations.', max_length=10),
        ),
        migrations.AddField(
            model_name='ziplocation',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ziplocation',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
