# Generated by Django 6.0 on 2025-12-09 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_globalsettings_base_zip_code_ziplocation_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='install_disclaimer_accepted',
            field=models.BooleanField(default=False, help_text='Customer acknowledged that install date is not guaranteed.'),
        ),
        migrations.AddField(
            model_name='order',
            name='install_queue_position',
            field=models.PositiveIntegerField(blank=True, help_text='Position in install queue for this county (1 = next in line).', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='install_service_area',
            field=models.ForeignKey(blank=True, help_text='County/service area used for install queue.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='install_orders', to='store.servicearea'),
        ),
    ]
