# Generated by Django 6.0 on 2025-12-09 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_order_install_disclaimer_accepted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='install_disclaimer_accepted',
        ),
        migrations.RemoveField(
            model_name='order',
            name='install_queue_position',
        ),
        migrations.RemoveField(
            model_name='order',
            name='install_service_area',
        ),
        migrations.AddField(
            model_name='servicearea',
            name='install_disclaimer_accepted',
            field=models.BooleanField(default=False, help_text='True once the customer has explicitly accepted the install scheduling disclaimer at checkout.'),
        ),
        migrations.AlterField(
            model_name='servicearea',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes about this order.'),
        ),
    ]
