# Generated by Django 6.0 on 2025-12-09 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_remove_order_install_disclaimer_accepted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='install_disclaimer_accepted',
            field=models.BooleanField(default=False, help_text='Customer has accepted the installation disclaimer for this order.'),
        ),
    ]
