# Generated by Django 6.0 on 2025-12-09 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_order_install_disclaimer_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='install_queue_position',
            field=models.PositiveIntegerField(blank=True, help_text='Position in the install queue within the service area.', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='install_service_area',
            field=models.ForeignKey(blank=True, help_text='Service area used for installation scheduling.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_for_install', to='store.servicearea'),
        ),
    ]
